//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opinionbar.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Members.OpinionBar.Components.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies who want your opinion.
        /// </summary>
        public static string about_msg {
            get {
                return ResourceManager.GetString("about_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least 6 characters.
        /// </summary>
        public static string atleast6letters {
            get {
                return ResourceManager.GetString("atleast6letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Sign in.
        /// </summary>
        public static string back_to_signin {
            get {
                return ResourceManager.GetString("back_to_signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bank account.
        /// </summary>
        public static string bankaccount {
            get {
                return ResourceManager.GetString("bankaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your opinion and get paid.
        /// </summary>
        public static string banner1_giveyouropinion {
            get {
                return ResourceManager.GetString("banner1_giveyouropinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And no spam... Promised!.
        /// </summary>
        public static string banner1_small_nospam {
            get {
                return ResourceManager.GetString("banner1_small_nospam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach of Terms.
        /// </summary>
        public static string breach_terms {
            get {
                return ResourceManager.GetString("breach_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If OpinionBar is of the reasonable opinion that a real or potential breach of the letter or intent of the terms and conditions has occurred, OpinionBar reserves the right to immediately either permanently or temporarily postpone or terminate the Services supplied by OpinionBar, to block prohibited activities or undertake any other actions it considers suitable. Users who violate these TERMS may also become criminally or civilly liable. OpinionBar may hand any perpetrators over to the civil or criminal autho [rest of string was truncated]&quot;;.
        /// </summary>
        public static string breach_terms_msg {
            get {
                return ResourceManager.GetString("breach_terms_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your country.
        /// </summary>
        public static string choose_country {
            get {
                return ResourceManager.GetString("choose_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose password.
        /// </summary>
        public static string choose_password {
            get {
                return ResourceManager.GetString("choose_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required.
        /// </summary>
        public static string choose_password_error_msg {
            get {
                return ResourceManager.GetString("choose_password_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a country….
        /// </summary>
        public static string cn_choose_country {
            get {
                return ResourceManager.GetString("cn_choose_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a survey….
        /// </summary>
        public static string cn_choose_survey {
            get {
                return ResourceManager.GetString("cn_choose_survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string cn_feeback_msg {
            get {
                return ResourceManager.GetString("cn_feeback_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string cn_full_name {
            get {
                return ResourceManager.GetString("cn_full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string cn_send_msg {
            get {
                return ResourceManager.GetString("cn_send_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string contact_header {
            get {
                return ResourceManager.GetString("contact_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpinionBar is not responsible for the contents parties (e.g. web sites, commercials, cookies, ads, tags, software) or products of third you visit as a participant of a survey, whether this is permitted by the laws for copyright, trade secrecy, slander, privacy, and obscenity or otherwise.&lt;/br&gt;
        ///You understand that by becoming a Panel Member and sometimes taking part in surveys you may have to view contents that may be insulting or inappropriate or infringe the right of ownership of a third party. You are the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string content_msg {
            get {
                return ResourceManager.GetString("content_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string creat_account {
            get {
                return ResourceManager.GetString("creat_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        public static string create_your_account {
            get {
                return ResourceManager.GetString("create_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Declaration of privacy.
        /// </summary>
        public static string dec_privacy {
            get {
                return ResourceManager.GetString("dec_privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By accepting the TERMS you explicitly accept OpinionBar&apos;s publication and use of your personal details as described in the then current&lt;/br&gt; OpinionBar Declaration of Privacy..
        /// </summary>
        public static string dec_privacy_msg {
            get {
                return ResourceManager.GetString("dec_privacy_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address..
        /// </summary>
        public static string email_error_msg1 {
            get {
                return ResourceManager.GetString("email_error_msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email Address field is required.
        /// </summary>
        public static string email_error_msg2 {
            get {
                return ResourceManager.GetString("email_error_msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry of the account.
        /// </summary>
        public static string expiry__account {
            get {
                return ResourceManager.GetString("expiry_ account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not actively take part in the OpinionBar Panel - if you do not respond to any email requests or take part in an available investigation - for a period of more than one month, OpinionBar has the right to close your account and any balance in your account will be considered &quot;not earned &quot; and will expire.&lt;/br&gt;
        ///OpinionBar and the OpinionBar Logo are trademarks of MetrixLab B.V. in The Netherlands and worldwide. All other trademarks are the property of their respective owners..
        /// </summary>
        public static string expiry__account_msg {
            get {
                return ResourceManager.GetString("expiry_ account_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First name field is required.
        /// </summary>
        public static string first_name_error_msg {
            get {
                return ResourceManager.GetString("first_name_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string footer_copyright_2015 {
            get {
                return ResourceManager.GetString("footer_copyright 2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about OpinionBar.
        /// </summary>
        public static string footer_more_abt_opbar {
            get {
                return ResourceManager.GetString("footer_more_abt_opbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string footer_privacy {
            get {
                return ResourceManager.GetString("footer_privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; conditions.
        /// </summary>
        public static string footer_terms_conditions {
            get {
                return ResourceManager.GetString("footer_terms&conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string forgot_psw {
            get {
                return ResourceManager.GetString("forgot_psw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your e-mail address and we will send you an e-mail with a special link which you can use to enter a new password for your account..
        /// </summary>
        public static string forgot_psw_msg {
            get {
                return ResourceManager.GetString("forgot_psw_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string forgot_your_psw {
            get {
                return ResourceManager.GetString("forgot_your_psw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TERMS are generated and drawn up in conformance with Dutch law as it applies to contracts entered into by Dutch inhabitants. If any condition(s) in the TERMS does/do not conform to the law, condition(s) will be drawn up that remain as close to the intentions of the parties as possible. The other provisions in this Agreement will remain fully applicable. If OpinionBar fails to execute or force the rights or provisions in the TERMS, this does not mean the TERMS have rejected such a right or provision, unl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string general_msg {
            get {
                return ResourceManager.GetString("general_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get paid!.
        /// </summary>
        public static string get_paid {
            get {
                return ResourceManager.GetString("get_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose to be paid or to support a charity of your choice.
        /// </summary>
        public static string get_paid_msg {
            get {
                return ResourceManager.GetString("get_paid_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your opinion.
        /// </summary>
        public static string give_your_opinion {
            get {
                return ResourceManager.GetString("give_your_opinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast your opinion in our online surveys and help companies to improve their products.
        /// </summary>
        public static string give_your_opinion_msg {
            get {
                return ResourceManager.GetString("give_your_opinion_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string how_it_works {
            get {
                return ResourceManager.GetString("how_it_works", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last name field is required.
        /// </summary>
        public static string last_name_error_msg {
            get {
                return ResourceManager.GetString("last_name_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitation of guarantees.
        /// </summary>
        public static string limitation__guarantees {
            get {
                return ResourceManager.GetString("limitation_ guarantees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpinionBar supplies the Research Panel, the services and all Evaluations &quot;as is&quot;. Neither OpinionBar, nor its branch offices, suppliers, channel partners or clients will make explicit or implicit statements about the functioning of information that has been made available through or via the Research Panel, the services and evaluations. OpinionBar rejects any liability, either explicitly or implicitly, including but not limited to implicit guarantees of saleability, ownership, suitability for a certain purpo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string limitation__guarantees_msg {
            get {
                return ResourceManager.GetString("limitation_ guarantees_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitation of liability.
        /// </summary>
        public static string limitation_liability {
            get {
                return ResourceManager.GetString("limitation_liability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In no event can OpinionBar, it&apos;s branch offices, suppliers, channel partners or clients be held responsible for any damage, including but not limited to direct, indirect and additional damage or consequential loss, either based on warranty, contract, illegal action or another legal theory and whether or not informed about the possibility of such damage. The total liability of OpinionBar, its branch offices, suppliers, channel partners or clients resulting from or with regards to this agreement (regardless o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string limitation_liability_msg {
            get {
                return ResourceManager.GetString("limitation_liability_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re a leading global online testing community. We’re operated by MetrixLab, one of the world&apos;s fastest growing digital market research agencies..&lt;/br&gt;
        ///We invite community members to participate in online surveys. They can do this from the comfort of their own home or from wherever they choose. And they get paid for taking the time to tell brands what they think..&lt;/br&gt;
        ///We started in 1999 running surveys about websites. Today, our members number in the hundreds of thousands and are asked for their views on  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string m_abt_msg {
            get {
                return ResourceManager.GetString("m_abt_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string menu_about {
            get {
                return ResourceManager.GetString("menu_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        public static string menu_contact {
            get {
                return ResourceManager.GetString("menu_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY PROFILE.
        /// </summary>
        public static string menu_profile {
            get {
                return ResourceManager.GetString("menu_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string mp_address {
            get {
                return ResourceManager.GetString("mp_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright!.
        /// </summary>
        public static string mp_alirght {
            get {
                return ResourceManager.GetString("mp_alirght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string mp_avaliable {
            get {
                return ResourceManager.GetString("mp_avaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string mp_balance {
            get {
                return ResourceManager.GetString("mp_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To my bank account.
        /// </summary>
        public static string mp_bank_account {
            get {
                return ResourceManager.GetString("mp_bank_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string mp_change {
            get {
                return ResourceManager.GetString("mp_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Payment Option.
        /// </summary>
        public static string mp_change_pay_option {
            get {
                return ResourceManager.GetString("mp_change_pay_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To a charity of my choice.
        /// </summary>
        public static string mp_charity {
            get {
                return ResourceManager.GetString("mp_charity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chose to pay your balance of.
        /// </summary>
        public static string mp_choose_pay_bal {
            get {
                return ResourceManager.GetString("mp_choose_pay_bal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string mp_city {
            get {
                return ResourceManager.GetString("mp_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string mp_close {
            get {
                return ResourceManager.GetString("mp_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Payment.
        /// </summary>
        public static string mp_confirm_payment {
            get {
                return ResourceManager.GetString("mp_confirm_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string mp_country {
            get {
                return ResourceManager.GetString("mp_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My details.
        /// </summary>
        public static string mp_deatails_tab {
            get {
                return ResourceManager.GetString("mp_deatails_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string mp_delete_account {
            get {
                return ResourceManager.GetString("mp_delete_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string mp_delete_account_msg1 {
            get {
                return ResourceManager.GetString("mp_delete_account_msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account? You can&apos;t recover your account later. Your remaining balance will be lost..
        /// </summary>
        public static string mp_delete_account_msg2 {
            get {
                return ResourceManager.GetString("mp_delete_account_msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are these payment details correct?.
        /// </summary>
        public static string mp_details_correct {
            get {
                return ResourceManager.GetString("mp_details_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth:.
        /// </summary>
        public static string mp_dob {
            get {
                return ResourceManager.GetString("mp_dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Paid.
        /// </summary>
        public static string mp_getpaid {
            get {
                return ResourceManager.GetString("mp_getpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string mp_history {
            get {
                return ResourceManager.GetString("mp_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN Number:.
        /// </summary>
        public static string mp_iban_number {
            get {
                return ResourceManager.GetString("mp_iban_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will invite you for more surveys soon!.
        /// </summary>
        public static string mp_invite_more_surveys {
            get {
                return ResourceManager.GetString("mp_invite_more_surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pay my balance of €10,00 to:.
        /// </summary>
        public static string mp_my_balance {
            get {
                return ResourceManager.GetString("mp_my_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string mp_name {
            get {
                return ResourceManager.GetString("mp_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string mp_password {
            get {
                return ResourceManager.GetString("mp_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string mp_pay_amount {
            get {
                return ResourceManager.GetString("mp_pay_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string mp_pay_date {
            get {
                return ResourceManager.GetString("mp_pay_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid to:.
        /// </summary>
        public static string mp_pay_paid {
            get {
                return ResourceManager.GetString("mp_pay_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string mp_pay_status {
            get {
                return ResourceManager.GetString("mp_pay_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string mp_pay_total {
            get {
                return ResourceManager.GetString("mp_pay_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payee name:.
        /// </summary>
        public static string mp_payer_name {
            get {
                return ResourceManager.GetString("mp_payer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment will be transferred to your acount in the first week of next month!.
        /// </summary>
        public static string mp_payment_confirmmation {
            get {
                return ResourceManager.GetString("mp_payment_confirmmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment History.
        /// </summary>
        public static string mp_payment_history {
            get {
                return ResourceManager.GetString("mp_payment_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Order.
        /// </summary>
        public static string mp_payment_order {
            get {
                return ResourceManager.GetString("mp_payment_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My payments.
        /// </summary>
        public static string mp_payment_text {
            get {
                return ResourceManager.GetString("mp_payment_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payments:.
        /// </summary>
        public static string mp_payments_text {
            get {
                return ResourceManager.GetString("mp_payments_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To my PayPal account.
        /// </summary>
        public static string mp_paypal_account {
            get {
                return ResourceManager.GetString("mp_paypal_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information.
        /// </summary>
        public static string mp_personal_info {
            get {
                return ResourceManager.GetString("mp_personal_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string mp_profile {
            get {
                return ResourceManager.GetString("mp_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing the next profile survey &quot;Survey name&quot; will bring your profile completeness to 60%.
        /// </summary>
        public static string mp_profile_text {
            get {
                return ResourceManager.GetString("mp_profile_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string mp_save {
            get {
                return ResourceManager.GetString("mp_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Survey.
        /// </summary>
        public static string mp_start_survey {
            get {
                return ResourceManager.GetString("mp_start_survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My surveys.
        /// </summary>
        public static string mp_survey_tab {
            get {
                return ResourceManager.GetString("mp_survey_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to your bank account:.
        /// </summary>
        public static string mp_to_bank_account {
            get {
                return ResourceManager.GetString("mp_to_bank_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already earned.
        /// </summary>
        public static string mp_totla_earned {
            get {
                return ResourceManager.GetString("mp_totla_earned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        public static string mp_welcome {
            get {
                return ResourceManager.GetString("mp_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reward!.
        /// </summary>
        public static string mp_your_reward {
            get {
                return ResourceManager.GetString("mp_your_reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code:.
        /// </summary>
        public static string mp_zip {
            get {
                return ResourceManager.GetString("mp_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about OpinionBar.
        /// </summary>
        public static string mr_abt_op {
            get {
                return ResourceManager.GetString("mr_abt_op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortune 500 companies!.
        /// </summary>
        public static string opbar_fortune__companies {
            get {
                return ResourceManager.GetString("opbar_fortune _companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We work together with Fortune 500 companies from all over the world..
        /// </summary>
        public static string opbar_fortune__companies_msg {
            get {
                return ResourceManager.GetString("opbar_fortune _companies_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We make your voice heard!.
        /// </summary>
        public static string opbar_make_your_voice {
            get {
                return ResourceManager.GetString("opbar_make_your_voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With OpinionBar, millions of people express their opinion every year and tell the large organizations what they think of their products, services, websites and advertisement..
        /// </summary>
        public static string opbar_make_your_voice_msg {
            get {
                return ResourceManager.GetString("opbar_make_your_voice_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy!.
        /// </summary>
        public static string opbar_privacy {
            get {
                return ResourceManager.GetString("opbar_privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpinionBar values the privacy of your personal data. That&apos;s why surveys are anonymous, we never share personal data with third parties and your data is protected by SSL..
        /// </summary>
        public static string opbar_privacy_msg {
            get {
                return ResourceManager.GetString("opbar_privacy_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpinionBar.
        /// </summary>
        public static string opinionbar {
            get {
                return ResourceManager.GetString("opinionbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password must be at least 6 characters.
        /// </summary>
        public static string password_length_error_msg {
            get {
                return ResourceManager.GetString("password_length_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passsword verification.
        /// </summary>
        public static string password_verifcation {
            get {
                return ResourceManager.GetString("password_verifcation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string password_verifcation_error_msg {
            get {
                return ResourceManager.GetString("password_verifcation_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        public static string paypal {
            get {
                return ResourceManager.GetString("paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal account.
        /// </summary>
        public static string paypalaccount {
            get {
                return ResourceManager.GetString("paypalaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The answers you give in our surveys, researches and on our website will be treated as anonymous, unless, and only unless, you have given your specific consent to the contrary. In the relatively few instances where we ask you for permission to pass data on in a form which allows you to be personally identified, we will ensure that the information will be used only for the purposes stated. We will not send you unsolicited commercial mail, nor pass on your email addresses to others for this purpose. However vi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string privacy_ans1 {
            get {
                return ResourceManager.GetString("privacy_ans1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This privacy policy applies to all persons which participate or have participated in researches by OpinionBar/MetrixLab: 1. Participants which have registered through the OpinionBar.com signup form. 2. Participants which are recruited by an invitation on third party websites. 3. Participants which are invited through a CRM database delivered by the client. 4. Participants which have been recruited through people’s choice awards organized by OpinionBar. 5. Participants which have participated to surveys in a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string privacy_ans2 {
            get {
                return ResourceManager.GetString("privacy_ans2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information such as your name, address, ip-address, email address, payment information, telephone number and date of birth is classed as &quot;recognisable personal information&quot; because this information can be used to indirectly or directly to identify you. This information is protected by virtue of our privacy policy. We will never give, sell, rent out, or trade recognisable personal information to a third party or share this information with a third party..
        /// </summary>
        public static string privacy_ans3 {
            get {
                return ResourceManager.GetString("privacy_ans3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys are always anonymous: your name, address and email details are never passed on to other companies or persons. This applies to the participants in our researches and surveys and is legally required for each survey.&lt;/br&gt;
        ///Information that can be traced back to a particular person will never be used for non-research purposes such as direct marketing, setting up address lists, credit rating, the collection of money or other marketing activities related to those individual respondents.&lt;/br&gt;
        ///We perform our [rest of string was truncated]&quot;;.
        /// </summary>
        public static string privacy_ans4 {
            get {
                return ResourceManager.GetString("privacy_ans4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OpinionBar website is protected against loss, misuse and editing of the information we manage. This includes measures such as firewalls, data scrambling, SSL encryption (RC4 128 Bits), application proxies, monitoring technology and adaptive analysis of network traffic to trace any abuse of our network and its data contents. The OpinionBar website and software communicate with our database using the SSL-protocol, thus ensuring third parties are not able to read or edit any data..
        /// </summary>
        public static string privacy_ans5 {
            get {
                return ResourceManager.GetString("privacy_ans5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can always visit our website and change your own profile. Please Note: You will be asked to give your email address and password if you wish to view, change or replace your profile..
        /// </summary>
        public static string privacy_ans6 {
            get {
                return ResourceManager.GetString("privacy_ans6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can terminate your membership via the Unsubscribe page (www.opinionbar.com/unsubscribe.aspx). You will be sent an email to confirm the cancellation of your account for security purposes..
        /// </summary>
        public static string privacy_ans7 {
            get {
                return ResourceManager.GetString("privacy_ans7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If we decide to change our privacy policy we will publish these changes on our Homepage or send our users an email with the changes to ensure our users are always aware which information we collect, how we use it, and under what circumstances we may publish this information..
        /// </summary>
        public static string privacy_ans8 {
            get {
                return ResourceManager.GetString("privacy_ans8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All research performed on the Internet is subject to the rules and initiatives of the leading ICC/ESOMAR International Code of Marketing and Social Research Practice (plus European Guideline for Data Protection and any other relevant national or international legislation).&lt;/br&gt;
        ///Market research must always respect the rights of the respondents and other Internet users. It must be executed in a way that is acceptable to all those involved and the general public and it must comply with national and internation [rest of string was truncated]&quot;;.
        /// </summary>
        public static string privacy_ans9 {
            get {
                return ResourceManager.GetString("privacy_ans9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpinionBar is an initiative of the digital research agency MetrixLab. MetrixLab (OpinionBar) collects information for the sole purpose of market research..&lt;/br&gt;
        ///Market research is the gathering and interpreting of information from consumers, companies and society. The intelligence collected is used by commissioning clients/companies to make smarter decisions with regards to marketing, product development and society. Your participation in the OpinionBar surveys helps companies to develop and improve website [rest of string was truncated]&quot;;.
        /// </summary>
        public static string privacy_msg {
            get {
                return ResourceManager.GetString("privacy_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does OpinionBar treat my data?.
        /// </summary>
        public static string privacy_qn1 {
            get {
                return ResourceManager.GetString("privacy_qn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To whom does this privacy statement apply to?.
        /// </summary>
        public static string privacy_qn2 {
            get {
                return ResourceManager.GetString("privacy_qn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of information do we collect from participants?.
        /// </summary>
        public static string privacy_qn3 {
            get {
                return ResourceManager.GetString("privacy_qn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How will we use this information?.
        /// </summary>
        public static string privacy_qn4 {
            get {
                return ResourceManager.GetString("privacy_qn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of security do we use to protect the information?.
        /// </summary>
        public static string privacy_qn5 {
            get {
                return ResourceManager.GetString("privacy_qn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can you access your personal details?.
        /// </summary>
        public static string privacy_qn6 {
            get {
                return ResourceManager.GetString("privacy_qn6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can you terminate your participation?.
        /// </summary>
        public static string privacy_qn7 {
            get {
                return ResourceManager.GetString("privacy_qn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do we inform you about changes in the privacy policy?.
        /// </summary>
        public static string privacy_qn8 {
            get {
                return ResourceManager.GetString("privacy_qn8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisations and regulations we conform to..
        /// </summary>
        public static string privacy_qn9 {
            get {
                return ResourceManager.GetString("privacy_qn9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not to mail to third parties or to otherwise publicise information about surveys, including but not limited to the questions asked, your response to the questions, the nature of the survey or content in any surveys you participated, websites you have visited, or products you have tested during your participation in a survey. Copyright on all content, questions and answers belongs to OpinionBar..
        /// </summary>
        public static string prohibited_list_1 {
            get {
                return ResourceManager.GetString("prohibited_list_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not to use &quot;auto-responders&quot;, &quot;cancel-bots&quot;, or similar mechanisms that solely generate network traffic or disturb newsgroups or email..
        /// </summary>
        public static string prohibited_list_10 {
            get {
                return ResourceManager.GetString("prohibited_list_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never to send unsolicited emails or advertisements..
        /// </summary>
        public static string prohibited_list_11 {
            get {
                return ResourceManager.GetString("prohibited_list_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not to send false or misleading offers of products, business or services, or: Not to pass on unsolicited emails or advertisements using OpinionBar servers&lt;/br&gt;.
        /// </summary>
        public static string prohibited_list_12 {
            get {
                return ResourceManager.GetString("prohibited_list_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not to have third parties fill in your surveys for you.
        /// </summary>
        public static string prohibited_list_13 {
            get {
                return ResourceManager.GetString("prohibited_list_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not to use software, or a mechanism that automatically generates answers in our surveys.
        /// </summary>
        public static string prohibited_list_14 {
            get {
                return ResourceManager.GetString("prohibited_list_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not to reregister yourself to OpinionBar once your account is deleted due to an infringement of our Terms and Conditions.
        /// </summary>
        public static string prohibited_list_15 {
            get {
                return ResourceManager.GetString("prohibited_list_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not to give misleading or false information during your registration or in your answers in a survey..
        /// </summary>
        public static string prohibited_list_2 {
            get {
                return ResourceManager.GetString("prohibited_list_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not to publicise misleading or false information regarding OpinionBar or its surveys..
        /// </summary>
        public static string prohibited_list_3 {
            get {
                return ResourceManager.GetString("prohibited_list_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not to encourage third parties to give OpinionBar incorrect or false information as part if the registration process..
        /// </summary>
        public static string prohibited_list_4 {
            get {
                return ResourceManager.GetString("prohibited_list_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not to demand rewards for surveys you have not completed in good faith..
        /// </summary>
        public static string prohibited_list_5 {
            get {
                return ResourceManager.GetString("prohibited_list_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not to use or send any material protected by copyright, trademark, trade secrecy, patent or other intellectual ownership rights without first gaining the appropriate authorisation.&lt;/br&gt;.
        /// </summary>
        public static string prohibited_list_6 {
            get {
                return ResourceManager.GetString("prohibited_list_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never to send an electronic transmission of a message subject, either partially or in its entirety, that originates from or runs through the Services..
        /// </summary>
        public static string prohibited_list_7 {
            get {
                return ResourceManager.GetString("prohibited_list_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never to threaten, pester, discredit, embarrass, or distress another person or group..
        /// </summary>
        public static string prohibited_list_8 {
            get {
                return ResourceManager.GetString("prohibited_list_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never to send any computer viruses, worms or other software with the intention of damaging or changing a computer system..
        /// </summary>
        public static string prohibited_list_9 {
            get {
                return ResourceManager.GetString("prohibited_list_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a Panel Member you agree to only use the Services for legal purposes. The use of Services for or with regards to the sending, distribution,collection or saving of data or material that is against the law or any other regulations is prohibited. You also agree:&lt;/br&gt;.
        /// </summary>
        public static string prohibited_use_msg {
            get {
                return ResourceManager.GetString("prohibited_use_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string rememberme {
            get {
                return ResourceManager.GetString("rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request link.
        /// </summary>
        public static string request_link {
            get {
                return ResourceManager.GetString("request_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibilities of the user.
        /// </summary>
        public static string resp_of_usr {
            get {
                return ResourceManager.GetString("resp_of_usr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You agree to provide OpinionBar with correct and complete registration details and to always keep these details up to date. You agree not to register as a Panel Member under more than one name, never to take part in the same survey twice, transfer your credits to a bank account other than your own or obtain more than one password in any way. Should you fail to do this, you are in contravention of these TERMS.&lt;/br&gt;
        ///You declare that you are not a partner, shareholder or employee of a company that offers softw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string resp_of_usr_msg {
            get {
                return ResourceManager.GetString("resp_of_usr_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safeguarding.
        /// </summary>
        public static string safeguarding {
            get {
                return ResourceManager.GetString("safeguarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You agree to safeguard OpinionBar, its branch offices, suppliers, channel partners and clients against any claims and demands, including legal fees, by third parties as the result of the use of your account, any contents you may post, mail, send or transfer in your capacity as Panel Member, your breach of the TERMS or your infringement of the rights of any third party..
        /// </summary>
        public static string safeguarding_msg {
            get {
                return ResourceManager.GetString("safeguarding_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string sign_out {
            get {
                return ResourceManager.GetString("sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email or Password.
        /// </summary>
        public static string signin_error_msg {
            get {
                return ResourceManager.GetString("signin_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in via Facebook.
        /// </summary>
        public static string signin_facebook {
            get {
                return ResourceManager.GetString("signin_facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in your account.
        /// </summary>
        public static string signin_your_acount {
            get {
                return ResourceManager.GetString("signin_your_acount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for free.
        /// </summary>
        public static string signup_free {
            get {
                return ResourceManager.GetString("signup_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your free OpinionBar account today and join our online community.
        /// </summary>
        public static string signup_free_msg {
            get {
                return ResourceManager.GetString("signup_free_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We believe surveys should be fun!.
        /// </summary>
        public static string srvy_shd_fun {
            get {
                return ResourceManager.GetString("srvy_shd_fun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a member of our community, you’ll be invited to participate in all kinds of surveys. We believe these should be as interesting and/or fun for you to complete as possible. After all, if you enjoy completing them, we achieve better response rates and higher quality data. For this reason, we often use game-like and fun exercises to determine what members really think about websites or advertisements, for example You’ll also have the opportunity to test products at home (and to keep them most of the time)...
        /// </summary>
        public static string srvy_shd_fun_msg {
            get {
                return ResourceManager.GetString("srvy_shd_fun_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System and Network security.
        /// </summary>
        public static string sys_network_sec {
            get {
                return ResourceManager.GetString("sys_network_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations of the system or network security of the Services or of a website you are visiting d uring a survey are prohibited and may make you become subject to criminal or civil law. OpinionBar will investigate any breaches of security and may inform the relevant police services if any violations are suspected. You are not permitted to evade authentications or the security of hosts, networks, network components or accounts to gain access to data, accounts or systems for which you have not received express  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sys_network_sec_msg {
            get {
                return ResourceManager.GetString("sys_network_sec_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Content.
        /// </summary>
        public static string tc_content {
            get {
                return ResourceManager.GetString("tc_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpinionBar carries out surveys using the members of the OpinionBar Research Panel (the &quot;Research Panel&quot;). The terms, conditions and guidelines that are tied to becoming a member of the Research Panel and the use of the OpinionBar Services, the OpinionBar Software and the related services (the &quot;Services&quot;) that are made available to the members of the Research Panel (&quot;Panel Members&quot;) are stated in these terms for participation in the OpinionBar Research Panel. (&quot;TERMS&quot;).&lt;/br&gt;
        ///By participating in an OpinionBar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tc_msg {
            get {
                return ResourceManager.GetString("tc_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prohibited use.
        /// </summary>
        public static string tc_prohibited_use {
            get {
                return ResourceManager.GetString("tc_prohibited_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination.
        /// </summary>
        public static string termination {
            get {
                return ResourceManager.GetString("termination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may terminate your account any time by visiting your account termination page or send a letter with your name, address, date of birth, email address and signature to: MetrixLab B.V., Wilhelminakade 312, 3072 AR, Rotterdam, The Netherlands. The termination of your account will occur within a reasonable time after OpinionBar has received your notice of termination.&lt;/br&gt;
        ///OpinionBar reserves the right to restrict the Services to users and from time to time and according to its own judgement with or without  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string termination_msg {
            get {
                return ResourceManager.GetString("termination_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We think you should be rewarded!.
        /// </summary>
        public static string we_thn_rewd {
            get {
                return ResourceManager.GetString("we_thn-rewd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will credit your account between €1.00 and €10.00 for each survey you complete. You can request a payment once your balance has reached the minimum threshold of €10.00 . You can choose to receive the money yourself or donate it to one of the charities supported by OpinionBar. Unlike other online survey communities, we reward you with money, not vouchers. It is your money and so you should be free to spend it however you choose...
        /// </summary>
        public static string we_thn_rewd_msg {
            get {
                return ResourceManager.GetString("we_thn-rewd_msg", resourceCulture);
            }
        }
    }
}
