version: 0.2

phases:
  install:
    commands:
      - echo Installing NuGet...
  build:
    commands:
      - nuget restore WL.PrecisionSample.sln
      - msbuild WL.PrecisionSample.sln /p:Configuration=Release
artifacts:
  files:
    - '**/bin/Release/**/*'
  discard-paths: yes
  base-directory: '.'
