//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Members.NewOpinionBar.Web.ra.imperium.com {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ra.imperium.com.raServiceSoap")]
    public interface raServiceSoap {
        
        // CODEGEN: Generating message contract since message AnalyzeAnswer6Request has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeAnswer6", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer6Response AnalyzeAnswer6(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer6Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeAnswer6", ReplyAction="*")]
        System.Threading.Tasks.Task<Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer6Response> AnalyzeAnswer6Async(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer6Request request);
        
        // CODEGEN: Generating message contract since message AnalyzeAnswer4Request has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeAnswer4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer4Response AnalyzeAnswer4(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer4Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeAnswer4", ReplyAction="*")]
        System.Threading.Tasks.Task<Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer4Response> AnalyzeAnswer4Async(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer4Request request);
        
        // CODEGEN: Generating message contract since message AnalyzeAnswer5Request has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeAnswer5", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer5Response AnalyzeAnswer5(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer5Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeAnswer5", ReplyAction="*")]
        System.Threading.Tasks.Task<Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer5Response> AnalyzeAnswer5Async(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer5Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeAnswerResponse4 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rASField;
        
        private string badWordsFlagField;
        
        private string garbageWordsFlagField;
        
        private string nonEngagedFlagField;
        
        private string pastedTextFlagField;
        
        private string robotFlagField;
        
        private string similarityFlagField;
        
        private string badPhraseFlagField;
        
        private string customFactor1FlagField;
        
        private string customFactor2FlagField;
        
        private string customFactor3FlagField;
        
        private string customFactor4FlagField;
        
        private string customFactor5FlagField;
        
        private string customFactor6FlagField;
        
        private string errorMsgField;
        
        private string uDF1Field;
        
        private string uDF2Field;
        
        private string uDF3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RAS {
            get {
                return this.rASField;
            }
            set {
                this.rASField = value;
                this.RaisePropertyChanged("RAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BadWordsFlag {
            get {
                return this.badWordsFlagField;
            }
            set {
                this.badWordsFlagField = value;
                this.RaisePropertyChanged("BadWordsFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string GarbageWordsFlag {
            get {
                return this.garbageWordsFlagField;
            }
            set {
                this.garbageWordsFlagField = value;
                this.RaisePropertyChanged("GarbageWordsFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NonEngagedFlag {
            get {
                return this.nonEngagedFlagField;
            }
            set {
                this.nonEngagedFlagField = value;
                this.RaisePropertyChanged("NonEngagedFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PastedTextFlag {
            get {
                return this.pastedTextFlagField;
            }
            set {
                this.pastedTextFlagField = value;
                this.RaisePropertyChanged("PastedTextFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RobotFlag {
            get {
                return this.robotFlagField;
            }
            set {
                this.robotFlagField = value;
                this.RaisePropertyChanged("RobotFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SimilarityFlag {
            get {
                return this.similarityFlagField;
            }
            set {
                this.similarityFlagField = value;
                this.RaisePropertyChanged("SimilarityFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BadPhraseFlag {
            get {
                return this.badPhraseFlagField;
            }
            set {
                this.badPhraseFlagField = value;
                this.RaisePropertyChanged("BadPhraseFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CustomFactor1Flag {
            get {
                return this.customFactor1FlagField;
            }
            set {
                this.customFactor1FlagField = value;
                this.RaisePropertyChanged("CustomFactor1Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CustomFactor2Flag {
            get {
                return this.customFactor2FlagField;
            }
            set {
                this.customFactor2FlagField = value;
                this.RaisePropertyChanged("CustomFactor2Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CustomFactor3Flag {
            get {
                return this.customFactor3FlagField;
            }
            set {
                this.customFactor3FlagField = value;
                this.RaisePropertyChanged("CustomFactor3Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CustomFactor4Flag {
            get {
                return this.customFactor4FlagField;
            }
            set {
                this.customFactor4FlagField = value;
                this.RaisePropertyChanged("CustomFactor4Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CustomFactor5Flag {
            get {
                return this.customFactor5FlagField;
            }
            set {
                this.customFactor5FlagField = value;
                this.RaisePropertyChanged("CustomFactor5Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CustomFactor6Flag {
            get {
                return this.customFactor6FlagField;
            }
            set {
                this.customFactor6FlagField = value;
                this.RaisePropertyChanged("CustomFactor6Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("ErrorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string UDF1 {
            get {
                return this.uDF1Field;
            }
            set {
                this.uDF1Field = value;
                this.RaisePropertyChanged("UDF1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string UDF2 {
            get {
                return this.uDF2Field;
            }
            set {
                this.uDF2Field = value;
                this.RaisePropertyChanged("UDF2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string UDF3 {
            get {
                return this.uDF3Field;
            }
            set {
                this.uDF3Field = value;
                this.RaisePropertyChanged("UDF3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeAnswerResponse6 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string relatedConfidenceScoreField;
        
        private string repeatedWordsPctField;
        
        private string detectedLanguageCodeField;
        
        private string rASField;
        
        private string badWordsFlagField;
        
        private string garbageWordsFlagField;
        
        private string nonEngagedFlagField;
        
        private string pastedTextFlagField;
        
        private string robotFlagField;
        
        private string similarityFlagField;
        
        private string badPhraseFlagField;
        
        private string customFactor1FlagField;
        
        private string customFactor2FlagField;
        
        private string customFactor3FlagField;
        
        private string customFactor4FlagField;
        
        private string customFactor5FlagField;
        
        private string customFactor6FlagField;
        
        private string errorMsgField;
        
        private string uDF1Field;
        
        private string uDF2Field;
        
        private string uDF3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RelatedConfidenceScore {
            get {
                return this.relatedConfidenceScoreField;
            }
            set {
                this.relatedConfidenceScoreField = value;
                this.RaisePropertyChanged("RelatedConfidenceScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RepeatedWordsPct {
            get {
                return this.repeatedWordsPctField;
            }
            set {
                this.repeatedWordsPctField = value;
                this.RaisePropertyChanged("RepeatedWordsPct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DetectedLanguageCode {
            get {
                return this.detectedLanguageCodeField;
            }
            set {
                this.detectedLanguageCodeField = value;
                this.RaisePropertyChanged("DetectedLanguageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RAS {
            get {
                return this.rASField;
            }
            set {
                this.rASField = value;
                this.RaisePropertyChanged("RAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BadWordsFlag {
            get {
                return this.badWordsFlagField;
            }
            set {
                this.badWordsFlagField = value;
                this.RaisePropertyChanged("BadWordsFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string GarbageWordsFlag {
            get {
                return this.garbageWordsFlagField;
            }
            set {
                this.garbageWordsFlagField = value;
                this.RaisePropertyChanged("GarbageWordsFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NonEngagedFlag {
            get {
                return this.nonEngagedFlagField;
            }
            set {
                this.nonEngagedFlagField = value;
                this.RaisePropertyChanged("NonEngagedFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PastedTextFlag {
            get {
                return this.pastedTextFlagField;
            }
            set {
                this.pastedTextFlagField = value;
                this.RaisePropertyChanged("PastedTextFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RobotFlag {
            get {
                return this.robotFlagField;
            }
            set {
                this.robotFlagField = value;
                this.RaisePropertyChanged("RobotFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SimilarityFlag {
            get {
                return this.similarityFlagField;
            }
            set {
                this.similarityFlagField = value;
                this.RaisePropertyChanged("SimilarityFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BadPhraseFlag {
            get {
                return this.badPhraseFlagField;
            }
            set {
                this.badPhraseFlagField = value;
                this.RaisePropertyChanged("BadPhraseFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CustomFactor1Flag {
            get {
                return this.customFactor1FlagField;
            }
            set {
                this.customFactor1FlagField = value;
                this.RaisePropertyChanged("CustomFactor1Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CustomFactor2Flag {
            get {
                return this.customFactor2FlagField;
            }
            set {
                this.customFactor2FlagField = value;
                this.RaisePropertyChanged("CustomFactor2Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CustomFactor3Flag {
            get {
                return this.customFactor3FlagField;
            }
            set {
                this.customFactor3FlagField = value;
                this.RaisePropertyChanged("CustomFactor3Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string CustomFactor4Flag {
            get {
                return this.customFactor4FlagField;
            }
            set {
                this.customFactor4FlagField = value;
                this.RaisePropertyChanged("CustomFactor4Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CustomFactor5Flag {
            get {
                return this.customFactor5FlagField;
            }
            set {
                this.customFactor5FlagField = value;
                this.RaisePropertyChanged("CustomFactor5Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CustomFactor6Flag {
            get {
                return this.customFactor6FlagField;
            }
            set {
                this.customFactor6FlagField = value;
                this.RaisePropertyChanged("CustomFactor6Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("ErrorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string UDF1 {
            get {
                return this.uDF1Field;
            }
            set {
                this.uDF1Field = value;
                this.RaisePropertyChanged("UDF1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string UDF2 {
            get {
                return this.uDF2Field;
            }
            set {
                this.uDF2Field = value;
                this.RaisePropertyChanged("UDF2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string UDF3 {
            get {
                return this.uDF3Field;
            }
            set {
                this.uDF3Field = value;
                this.RaisePropertyChanged("UDF3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnalyzeAnswer6", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AnalyzeAnswer6Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Members.NewOpinionBar.Web.ra.imperium.com.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ClientID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SurveyID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string QuestionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string AnswerText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LanguageCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string ra_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string ra_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string ra_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string ra_4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string RespondentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string EngagedLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string SuppressSimilarity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string CheckCustomFactor1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string CheckCustomFactor2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string CheckCustomFactor3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public string CheckCustomFactor4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=16)]
        public string CheckCustomFactor5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=17)]
        public string CheckCustomFactor6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=18)]
        public string BillingCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=19)]
        public string UDF1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=20)]
        public string UDF2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=21)]
        public string TextClassQuestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=22)]
        public string AutocorrectText;
        
        public AnalyzeAnswer6Request() {
        }
        
        public AnalyzeAnswer6Request(
                    Members.NewOpinionBar.Web.ra.imperium.com.AuthHeader AuthHeader, 
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6, 
                    string BillingCode, 
                    string UDF1, 
                    string UDF2, 
                    string TextClassQuestID, 
                    string AutocorrectText) {
            this.AuthHeader = AuthHeader;
            this.ClientID = ClientID;
            this.SurveyID = SurveyID;
            this.QuestionID = QuestionID;
            this.AnswerText = AnswerText;
            this.LanguageCode = LanguageCode;
            this.ra_1 = ra_1;
            this.ra_2 = ra_2;
            this.ra_3 = ra_3;
            this.ra_4 = ra_4;
            this.RespondentID = RespondentID;
            this.EngagedLength = EngagedLength;
            this.SuppressSimilarity = SuppressSimilarity;
            this.CheckCustomFactor1 = CheckCustomFactor1;
            this.CheckCustomFactor2 = CheckCustomFactor2;
            this.CheckCustomFactor3 = CheckCustomFactor3;
            this.CheckCustomFactor4 = CheckCustomFactor4;
            this.CheckCustomFactor5 = CheckCustomFactor5;
            this.CheckCustomFactor6 = CheckCustomFactor6;
            this.BillingCode = BillingCode;
            this.UDF1 = UDF1;
            this.UDF2 = UDF2;
            this.TextClassQuestID = TextClassQuestID;
            this.AutocorrectText = AutocorrectText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnalyzeAnswer6Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AnalyzeAnswer6Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswerResponse6 AnalyzeAnswer6Result;
        
        public AnalyzeAnswer6Response() {
        }
        
        public AnalyzeAnswer6Response(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswerResponse6 AnalyzeAnswer6Result) {
            this.AnalyzeAnswer6Result = AnalyzeAnswer6Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnalyzeAnswer4", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AnalyzeAnswer4Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Members.NewOpinionBar.Web.ra.imperium.com.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ClientID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SurveyID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string QuestionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string AnswerText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LanguageCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string ra_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string ra_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string ra_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string ra_4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string RespondentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string EngagedLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string SuppressSimilarity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string CheckCustomFactor1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string CheckCustomFactor2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string CheckCustomFactor3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public string CheckCustomFactor4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=16)]
        public string CheckCustomFactor5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=17)]
        public string CheckCustomFactor6;
        
        public AnalyzeAnswer4Request() {
        }
        
        public AnalyzeAnswer4Request(
                    Members.NewOpinionBar.Web.ra.imperium.com.AuthHeader AuthHeader, 
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6) {
            this.AuthHeader = AuthHeader;
            this.ClientID = ClientID;
            this.SurveyID = SurveyID;
            this.QuestionID = QuestionID;
            this.AnswerText = AnswerText;
            this.LanguageCode = LanguageCode;
            this.ra_1 = ra_1;
            this.ra_2 = ra_2;
            this.ra_3 = ra_3;
            this.ra_4 = ra_4;
            this.RespondentID = RespondentID;
            this.EngagedLength = EngagedLength;
            this.SuppressSimilarity = SuppressSimilarity;
            this.CheckCustomFactor1 = CheckCustomFactor1;
            this.CheckCustomFactor2 = CheckCustomFactor2;
            this.CheckCustomFactor3 = CheckCustomFactor3;
            this.CheckCustomFactor4 = CheckCustomFactor4;
            this.CheckCustomFactor5 = CheckCustomFactor5;
            this.CheckCustomFactor6 = CheckCustomFactor6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnalyzeAnswer4Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AnalyzeAnswer4Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswerResponse4 AnalyzeAnswer4Result;
        
        public AnalyzeAnswer4Response() {
        }
        
        public AnalyzeAnswer4Response(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswerResponse4 AnalyzeAnswer4Result) {
            this.AnalyzeAnswer4Result = AnalyzeAnswer4Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnalyzeAnswer5", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AnalyzeAnswer5Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Members.NewOpinionBar.Web.ra.imperium.com.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ClientID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SurveyID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string QuestionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string AnswerText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LanguageCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string ra_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string ra_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string ra_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string ra_4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string RespondentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string EngagedLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string SuppressSimilarity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string CheckCustomFactor1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string CheckCustomFactor2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string CheckCustomFactor3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public string CheckCustomFactor4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=16)]
        public string CheckCustomFactor5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=17)]
        public string CheckCustomFactor6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=18)]
        public string BillingCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=19)]
        public string UDF1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=20)]
        public string UDF2;
        
        public AnalyzeAnswer5Request() {
        }
        
        public AnalyzeAnswer5Request(
                    Members.NewOpinionBar.Web.ra.imperium.com.AuthHeader AuthHeader, 
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6, 
                    string BillingCode, 
                    string UDF1, 
                    string UDF2) {
            this.AuthHeader = AuthHeader;
            this.ClientID = ClientID;
            this.SurveyID = SurveyID;
            this.QuestionID = QuestionID;
            this.AnswerText = AnswerText;
            this.LanguageCode = LanguageCode;
            this.ra_1 = ra_1;
            this.ra_2 = ra_2;
            this.ra_3 = ra_3;
            this.ra_4 = ra_4;
            this.RespondentID = RespondentID;
            this.EngagedLength = EngagedLength;
            this.SuppressSimilarity = SuppressSimilarity;
            this.CheckCustomFactor1 = CheckCustomFactor1;
            this.CheckCustomFactor2 = CheckCustomFactor2;
            this.CheckCustomFactor3 = CheckCustomFactor3;
            this.CheckCustomFactor4 = CheckCustomFactor4;
            this.CheckCustomFactor5 = CheckCustomFactor5;
            this.CheckCustomFactor6 = CheckCustomFactor6;
            this.BillingCode = BillingCode;
            this.UDF1 = UDF1;
            this.UDF2 = UDF2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnalyzeAnswer5Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AnalyzeAnswer5Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswerResponse4 AnalyzeAnswer5Result;
        
        public AnalyzeAnswer5Response() {
        }
        
        public AnalyzeAnswer5Response(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswerResponse4 AnalyzeAnswer5Result) {
            this.AnalyzeAnswer5Result = AnalyzeAnswer5Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface raServiceSoapChannel : Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class raServiceSoapClient : System.ServiceModel.ClientBase<Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap>, Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap {
        
        public raServiceSoapClient() {
        }
        
        public raServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public raServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public raServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public raServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer6Response Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap.AnalyzeAnswer6(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer6Request request) {
            return base.Channel.AnalyzeAnswer6(request);
        }
        
        public Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswerResponse6 AnalyzeAnswer6(
                    Members.NewOpinionBar.Web.ra.imperium.com.AuthHeader AuthHeader, 
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6, 
                    string BillingCode, 
                    string UDF1, 
                    string UDF2, 
                    string TextClassQuestID, 
                    string AutocorrectText) {
            Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer6Request inValue = new Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer6Request();
            inValue.AuthHeader = AuthHeader;
            inValue.ClientID = ClientID;
            inValue.SurveyID = SurveyID;
            inValue.QuestionID = QuestionID;
            inValue.AnswerText = AnswerText;
            inValue.LanguageCode = LanguageCode;
            inValue.ra_1 = ra_1;
            inValue.ra_2 = ra_2;
            inValue.ra_3 = ra_3;
            inValue.ra_4 = ra_4;
            inValue.RespondentID = RespondentID;
            inValue.EngagedLength = EngagedLength;
            inValue.SuppressSimilarity = SuppressSimilarity;
            inValue.CheckCustomFactor1 = CheckCustomFactor1;
            inValue.CheckCustomFactor2 = CheckCustomFactor2;
            inValue.CheckCustomFactor3 = CheckCustomFactor3;
            inValue.CheckCustomFactor4 = CheckCustomFactor4;
            inValue.CheckCustomFactor5 = CheckCustomFactor5;
            inValue.CheckCustomFactor6 = CheckCustomFactor6;
            inValue.BillingCode = BillingCode;
            inValue.UDF1 = UDF1;
            inValue.UDF2 = UDF2;
            inValue.TextClassQuestID = TextClassQuestID;
            inValue.AutocorrectText = AutocorrectText;
            Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer6Response retVal = ((Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap)(this)).AnalyzeAnswer6(inValue);
            return retVal.AnalyzeAnswer6Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer6Response> Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap.AnalyzeAnswer6Async(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer6Request request) {
            return base.Channel.AnalyzeAnswer6Async(request);
        }
        
        public System.Threading.Tasks.Task<Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer6Response> AnalyzeAnswer6Async(
                    Members.NewOpinionBar.Web.ra.imperium.com.AuthHeader AuthHeader, 
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6, 
                    string BillingCode, 
                    string UDF1, 
                    string UDF2, 
                    string TextClassQuestID, 
                    string AutocorrectText) {
            Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer6Request inValue = new Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer6Request();
            inValue.AuthHeader = AuthHeader;
            inValue.ClientID = ClientID;
            inValue.SurveyID = SurveyID;
            inValue.QuestionID = QuestionID;
            inValue.AnswerText = AnswerText;
            inValue.LanguageCode = LanguageCode;
            inValue.ra_1 = ra_1;
            inValue.ra_2 = ra_2;
            inValue.ra_3 = ra_3;
            inValue.ra_4 = ra_4;
            inValue.RespondentID = RespondentID;
            inValue.EngagedLength = EngagedLength;
            inValue.SuppressSimilarity = SuppressSimilarity;
            inValue.CheckCustomFactor1 = CheckCustomFactor1;
            inValue.CheckCustomFactor2 = CheckCustomFactor2;
            inValue.CheckCustomFactor3 = CheckCustomFactor3;
            inValue.CheckCustomFactor4 = CheckCustomFactor4;
            inValue.CheckCustomFactor5 = CheckCustomFactor5;
            inValue.CheckCustomFactor6 = CheckCustomFactor6;
            inValue.BillingCode = BillingCode;
            inValue.UDF1 = UDF1;
            inValue.UDF2 = UDF2;
            inValue.TextClassQuestID = TextClassQuestID;
            inValue.AutocorrectText = AutocorrectText;
            return ((Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap)(this)).AnalyzeAnswer6Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer4Response Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap.AnalyzeAnswer4(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer4Request request) {
            return base.Channel.AnalyzeAnswer4(request);
        }
        
        public Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswerResponse4 AnalyzeAnswer4(
                    Members.NewOpinionBar.Web.ra.imperium.com.AuthHeader AuthHeader, 
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6) {
            Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer4Request inValue = new Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer4Request();
            inValue.AuthHeader = AuthHeader;
            inValue.ClientID = ClientID;
            inValue.SurveyID = SurveyID;
            inValue.QuestionID = QuestionID;
            inValue.AnswerText = AnswerText;
            inValue.LanguageCode = LanguageCode;
            inValue.ra_1 = ra_1;
            inValue.ra_2 = ra_2;
            inValue.ra_3 = ra_3;
            inValue.ra_4 = ra_4;
            inValue.RespondentID = RespondentID;
            inValue.EngagedLength = EngagedLength;
            inValue.SuppressSimilarity = SuppressSimilarity;
            inValue.CheckCustomFactor1 = CheckCustomFactor1;
            inValue.CheckCustomFactor2 = CheckCustomFactor2;
            inValue.CheckCustomFactor3 = CheckCustomFactor3;
            inValue.CheckCustomFactor4 = CheckCustomFactor4;
            inValue.CheckCustomFactor5 = CheckCustomFactor5;
            inValue.CheckCustomFactor6 = CheckCustomFactor6;
            Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer4Response retVal = ((Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap)(this)).AnalyzeAnswer4(inValue);
            return retVal.AnalyzeAnswer4Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer4Response> Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap.AnalyzeAnswer4Async(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer4Request request) {
            return base.Channel.AnalyzeAnswer4Async(request);
        }
        
        public System.Threading.Tasks.Task<Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer4Response> AnalyzeAnswer4Async(
                    Members.NewOpinionBar.Web.ra.imperium.com.AuthHeader AuthHeader, 
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6) {
            Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer4Request inValue = new Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer4Request();
            inValue.AuthHeader = AuthHeader;
            inValue.ClientID = ClientID;
            inValue.SurveyID = SurveyID;
            inValue.QuestionID = QuestionID;
            inValue.AnswerText = AnswerText;
            inValue.LanguageCode = LanguageCode;
            inValue.ra_1 = ra_1;
            inValue.ra_2 = ra_2;
            inValue.ra_3 = ra_3;
            inValue.ra_4 = ra_4;
            inValue.RespondentID = RespondentID;
            inValue.EngagedLength = EngagedLength;
            inValue.SuppressSimilarity = SuppressSimilarity;
            inValue.CheckCustomFactor1 = CheckCustomFactor1;
            inValue.CheckCustomFactor2 = CheckCustomFactor2;
            inValue.CheckCustomFactor3 = CheckCustomFactor3;
            inValue.CheckCustomFactor4 = CheckCustomFactor4;
            inValue.CheckCustomFactor5 = CheckCustomFactor5;
            inValue.CheckCustomFactor6 = CheckCustomFactor6;
            return ((Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap)(this)).AnalyzeAnswer4Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer5Response Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap.AnalyzeAnswer5(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer5Request request) {
            return base.Channel.AnalyzeAnswer5(request);
        }
        
        public Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswerResponse4 AnalyzeAnswer5(
                    Members.NewOpinionBar.Web.ra.imperium.com.AuthHeader AuthHeader, 
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6, 
                    string BillingCode, 
                    string UDF1, 
                    string UDF2) {
            Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer5Request inValue = new Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer5Request();
            inValue.AuthHeader = AuthHeader;
            inValue.ClientID = ClientID;
            inValue.SurveyID = SurveyID;
            inValue.QuestionID = QuestionID;
            inValue.AnswerText = AnswerText;
            inValue.LanguageCode = LanguageCode;
            inValue.ra_1 = ra_1;
            inValue.ra_2 = ra_2;
            inValue.ra_3 = ra_3;
            inValue.ra_4 = ra_4;
            inValue.RespondentID = RespondentID;
            inValue.EngagedLength = EngagedLength;
            inValue.SuppressSimilarity = SuppressSimilarity;
            inValue.CheckCustomFactor1 = CheckCustomFactor1;
            inValue.CheckCustomFactor2 = CheckCustomFactor2;
            inValue.CheckCustomFactor3 = CheckCustomFactor3;
            inValue.CheckCustomFactor4 = CheckCustomFactor4;
            inValue.CheckCustomFactor5 = CheckCustomFactor5;
            inValue.CheckCustomFactor6 = CheckCustomFactor6;
            inValue.BillingCode = BillingCode;
            inValue.UDF1 = UDF1;
            inValue.UDF2 = UDF2;
            Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer5Response retVal = ((Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap)(this)).AnalyzeAnswer5(inValue);
            return retVal.AnalyzeAnswer5Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer5Response> Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap.AnalyzeAnswer5Async(Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer5Request request) {
            return base.Channel.AnalyzeAnswer5Async(request);
        }
        
        public System.Threading.Tasks.Task<Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer5Response> AnalyzeAnswer5Async(
                    Members.NewOpinionBar.Web.ra.imperium.com.AuthHeader AuthHeader, 
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6, 
                    string BillingCode, 
                    string UDF1, 
                    string UDF2) {
            Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer5Request inValue = new Members.NewOpinionBar.Web.ra.imperium.com.AnalyzeAnswer5Request();
            inValue.AuthHeader = AuthHeader;
            inValue.ClientID = ClientID;
            inValue.SurveyID = SurveyID;
            inValue.QuestionID = QuestionID;
            inValue.AnswerText = AnswerText;
            inValue.LanguageCode = LanguageCode;
            inValue.ra_1 = ra_1;
            inValue.ra_2 = ra_2;
            inValue.ra_3 = ra_3;
            inValue.ra_4 = ra_4;
            inValue.RespondentID = RespondentID;
            inValue.EngagedLength = EngagedLength;
            inValue.SuppressSimilarity = SuppressSimilarity;
            inValue.CheckCustomFactor1 = CheckCustomFactor1;
            inValue.CheckCustomFactor2 = CheckCustomFactor2;
            inValue.CheckCustomFactor3 = CheckCustomFactor3;
            inValue.CheckCustomFactor4 = CheckCustomFactor4;
            inValue.CheckCustomFactor5 = CheckCustomFactor5;
            inValue.CheckCustomFactor6 = CheckCustomFactor6;
            inValue.BillingCode = BillingCode;
            inValue.UDF1 = UDF1;
            inValue.UDF2 = UDF2;
            return ((Members.NewOpinionBar.Web.ra.imperium.com.raServiceSoap)(this)).AnalyzeAnswer5Async(inValue);
        }
    }
}
