//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Members.NewOpinionBar.Web.com.imperium.ra {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="raServiceSoap", Namespace="http://tempuri.org/")]
    public partial class raService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback AnalyzeAnswer6OperationCompleted;
        
        private System.Threading.SendOrPostCallback AnalyzeAnswer4OperationCompleted;
        
        private System.Threading.SendOrPostCallback AnalyzeAnswer5OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public raService() {
            this.Url = global::Members.NewOpinionBar.Web.Properties.Settings.Default.Members_NewOpinionBar_Web_com_imperium_ra_raService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AnalyzeAnswer6CompletedEventHandler AnalyzeAnswer6Completed;
        
        /// <remarks/>
        public event AnalyzeAnswer4CompletedEventHandler AnalyzeAnswer4Completed;
        
        /// <remarks/>
        public event AnalyzeAnswer5CompletedEventHandler AnalyzeAnswer5Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AnalyzeAnswer6", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AnalyzeAnswerResponse6 AnalyzeAnswer6(
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6, 
                    string BillingCode, 
                    string UDF1, 
                    string UDF2, 
                    string TextClassQuestID, 
                    string AutocorrectText) {
            object[] results = this.Invoke("AnalyzeAnswer6", new object[] {
                        ClientID,
                        SurveyID,
                        QuestionID,
                        AnswerText,
                        LanguageCode,
                        ra_1,
                        ra_2,
                        ra_3,
                        ra_4,
                        RespondentID,
                        EngagedLength,
                        SuppressSimilarity,
                        CheckCustomFactor1,
                        CheckCustomFactor2,
                        CheckCustomFactor3,
                        CheckCustomFactor4,
                        CheckCustomFactor5,
                        CheckCustomFactor6,
                        BillingCode,
                        UDF1,
                        UDF2,
                        TextClassQuestID,
                        AutocorrectText});
            return ((AnalyzeAnswerResponse6)(results[0]));
        }
        
        /// <remarks/>
        public void AnalyzeAnswer6Async(
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6, 
                    string BillingCode, 
                    string UDF1, 
                    string UDF2, 
                    string TextClassQuestID, 
                    string AutocorrectText) {
            this.AnalyzeAnswer6Async(ClientID, SurveyID, QuestionID, AnswerText, LanguageCode, ra_1, ra_2, ra_3, ra_4, RespondentID, EngagedLength, SuppressSimilarity, CheckCustomFactor1, CheckCustomFactor2, CheckCustomFactor3, CheckCustomFactor4, CheckCustomFactor5, CheckCustomFactor6, BillingCode, UDF1, UDF2, TextClassQuestID, AutocorrectText, null);
        }
        
        /// <remarks/>
        public void AnalyzeAnswer6Async(
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6, 
                    string BillingCode, 
                    string UDF1, 
                    string UDF2, 
                    string TextClassQuestID, 
                    string AutocorrectText, 
                    object userState) {
            if ((this.AnalyzeAnswer6OperationCompleted == null)) {
                this.AnalyzeAnswer6OperationCompleted = new System.Threading.SendOrPostCallback(this.OnAnalyzeAnswer6OperationCompleted);
            }
            this.InvokeAsync("AnalyzeAnswer6", new object[] {
                        ClientID,
                        SurveyID,
                        QuestionID,
                        AnswerText,
                        LanguageCode,
                        ra_1,
                        ra_2,
                        ra_3,
                        ra_4,
                        RespondentID,
                        EngagedLength,
                        SuppressSimilarity,
                        CheckCustomFactor1,
                        CheckCustomFactor2,
                        CheckCustomFactor3,
                        CheckCustomFactor4,
                        CheckCustomFactor5,
                        CheckCustomFactor6,
                        BillingCode,
                        UDF1,
                        UDF2,
                        TextClassQuestID,
                        AutocorrectText}, this.AnalyzeAnswer6OperationCompleted, userState);
        }
        
        private void OnAnalyzeAnswer6OperationCompleted(object arg) {
            if ((this.AnalyzeAnswer6Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AnalyzeAnswer6Completed(this, new AnalyzeAnswer6CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AnalyzeAnswer4", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AnalyzeAnswerResponse4 AnalyzeAnswer4(
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6) {
            object[] results = this.Invoke("AnalyzeAnswer4", new object[] {
                        ClientID,
                        SurveyID,
                        QuestionID,
                        AnswerText,
                        LanguageCode,
                        ra_1,
                        ra_2,
                        ra_3,
                        ra_4,
                        RespondentID,
                        EngagedLength,
                        SuppressSimilarity,
                        CheckCustomFactor1,
                        CheckCustomFactor2,
                        CheckCustomFactor3,
                        CheckCustomFactor4,
                        CheckCustomFactor5,
                        CheckCustomFactor6});
            return ((AnalyzeAnswerResponse4)(results[0]));
        }
        
        /// <remarks/>
        public void AnalyzeAnswer4Async(
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6) {
            this.AnalyzeAnswer4Async(ClientID, SurveyID, QuestionID, AnswerText, LanguageCode, ra_1, ra_2, ra_3, ra_4, RespondentID, EngagedLength, SuppressSimilarity, CheckCustomFactor1, CheckCustomFactor2, CheckCustomFactor3, CheckCustomFactor4, CheckCustomFactor5, CheckCustomFactor6, null);
        }
        
        /// <remarks/>
        public void AnalyzeAnswer4Async(
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6, 
                    object userState) {
            if ((this.AnalyzeAnswer4OperationCompleted == null)) {
                this.AnalyzeAnswer4OperationCompleted = new System.Threading.SendOrPostCallback(this.OnAnalyzeAnswer4OperationCompleted);
            }
            this.InvokeAsync("AnalyzeAnswer4", new object[] {
                        ClientID,
                        SurveyID,
                        QuestionID,
                        AnswerText,
                        LanguageCode,
                        ra_1,
                        ra_2,
                        ra_3,
                        ra_4,
                        RespondentID,
                        EngagedLength,
                        SuppressSimilarity,
                        CheckCustomFactor1,
                        CheckCustomFactor2,
                        CheckCustomFactor3,
                        CheckCustomFactor4,
                        CheckCustomFactor5,
                        CheckCustomFactor6}, this.AnalyzeAnswer4OperationCompleted, userState);
        }
        
        private void OnAnalyzeAnswer4OperationCompleted(object arg) {
            if ((this.AnalyzeAnswer4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AnalyzeAnswer4Completed(this, new AnalyzeAnswer4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AnalyzeAnswer5", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AnalyzeAnswerResponse4 AnalyzeAnswer5(
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6, 
                    string BillingCode, 
                    string UDF1, 
                    string UDF2) {
            object[] results = this.Invoke("AnalyzeAnswer5", new object[] {
                        ClientID,
                        SurveyID,
                        QuestionID,
                        AnswerText,
                        LanguageCode,
                        ra_1,
                        ra_2,
                        ra_3,
                        ra_4,
                        RespondentID,
                        EngagedLength,
                        SuppressSimilarity,
                        CheckCustomFactor1,
                        CheckCustomFactor2,
                        CheckCustomFactor3,
                        CheckCustomFactor4,
                        CheckCustomFactor5,
                        CheckCustomFactor6,
                        BillingCode,
                        UDF1,
                        UDF2});
            return ((AnalyzeAnswerResponse4)(results[0]));
        }
        
        /// <remarks/>
        public void AnalyzeAnswer5Async(
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6, 
                    string BillingCode, 
                    string UDF1, 
                    string UDF2) {
            this.AnalyzeAnswer5Async(ClientID, SurveyID, QuestionID, AnswerText, LanguageCode, ra_1, ra_2, ra_3, ra_4, RespondentID, EngagedLength, SuppressSimilarity, CheckCustomFactor1, CheckCustomFactor2, CheckCustomFactor3, CheckCustomFactor4, CheckCustomFactor5, CheckCustomFactor6, BillingCode, UDF1, UDF2, null);
        }
        
        /// <remarks/>
        public void AnalyzeAnswer5Async(
                    string ClientID, 
                    string SurveyID, 
                    string QuestionID, 
                    string AnswerText, 
                    string LanguageCode, 
                    string ra_1, 
                    string ra_2, 
                    string ra_3, 
                    string ra_4, 
                    string RespondentID, 
                    string EngagedLength, 
                    string SuppressSimilarity, 
                    string CheckCustomFactor1, 
                    string CheckCustomFactor2, 
                    string CheckCustomFactor3, 
                    string CheckCustomFactor4, 
                    string CheckCustomFactor5, 
                    string CheckCustomFactor6, 
                    string BillingCode, 
                    string UDF1, 
                    string UDF2, 
                    object userState) {
            if ((this.AnalyzeAnswer5OperationCompleted == null)) {
                this.AnalyzeAnswer5OperationCompleted = new System.Threading.SendOrPostCallback(this.OnAnalyzeAnswer5OperationCompleted);
            }
            this.InvokeAsync("AnalyzeAnswer5", new object[] {
                        ClientID,
                        SurveyID,
                        QuestionID,
                        AnswerText,
                        LanguageCode,
                        ra_1,
                        ra_2,
                        ra_3,
                        ra_4,
                        RespondentID,
                        EngagedLength,
                        SuppressSimilarity,
                        CheckCustomFactor1,
                        CheckCustomFactor2,
                        CheckCustomFactor3,
                        CheckCustomFactor4,
                        CheckCustomFactor5,
                        CheckCustomFactor6,
                        BillingCode,
                        UDF1,
                        UDF2}, this.AnalyzeAnswer5OperationCompleted, userState);
        }
        
        private void OnAnalyzeAnswer5OperationCompleted(object arg) {
            if ((this.AnalyzeAnswer5Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AnalyzeAnswer5Completed(this, new AnalyzeAnswer5CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeAnswerResponse4 {
        
        private string rASField;
        
        private string badWordsFlagField;
        
        private string garbageWordsFlagField;
        
        private string nonEngagedFlagField;
        
        private string pastedTextFlagField;
        
        private string robotFlagField;
        
        private string similarityFlagField;
        
        private string badPhraseFlagField;
        
        private string customFactor1FlagField;
        
        private string customFactor2FlagField;
        
        private string customFactor3FlagField;
        
        private string customFactor4FlagField;
        
        private string customFactor5FlagField;
        
        private string customFactor6FlagField;
        
        private string errorMsgField;
        
        private string uDF1Field;
        
        private string uDF2Field;
        
        private string uDF3Field;
        
        /// <remarks/>
        public string RAS {
            get {
                return this.rASField;
            }
            set {
                this.rASField = value;
            }
        }
        
        /// <remarks/>
        public string BadWordsFlag {
            get {
                return this.badWordsFlagField;
            }
            set {
                this.badWordsFlagField = value;
            }
        }
        
        /// <remarks/>
        public string GarbageWordsFlag {
            get {
                return this.garbageWordsFlagField;
            }
            set {
                this.garbageWordsFlagField = value;
            }
        }
        
        /// <remarks/>
        public string NonEngagedFlag {
            get {
                return this.nonEngagedFlagField;
            }
            set {
                this.nonEngagedFlagField = value;
            }
        }
        
        /// <remarks/>
        public string PastedTextFlag {
            get {
                return this.pastedTextFlagField;
            }
            set {
                this.pastedTextFlagField = value;
            }
        }
        
        /// <remarks/>
        public string RobotFlag {
            get {
                return this.robotFlagField;
            }
            set {
                this.robotFlagField = value;
            }
        }
        
        /// <remarks/>
        public string SimilarityFlag {
            get {
                return this.similarityFlagField;
            }
            set {
                this.similarityFlagField = value;
            }
        }
        
        /// <remarks/>
        public string BadPhraseFlag {
            get {
                return this.badPhraseFlagField;
            }
            set {
                this.badPhraseFlagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomFactor1Flag {
            get {
                return this.customFactor1FlagField;
            }
            set {
                this.customFactor1FlagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomFactor2Flag {
            get {
                return this.customFactor2FlagField;
            }
            set {
                this.customFactor2FlagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomFactor3Flag {
            get {
                return this.customFactor3FlagField;
            }
            set {
                this.customFactor3FlagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomFactor4Flag {
            get {
                return this.customFactor4FlagField;
            }
            set {
                this.customFactor4FlagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomFactor5Flag {
            get {
                return this.customFactor5FlagField;
            }
            set {
                this.customFactor5FlagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomFactor6Flag {
            get {
                return this.customFactor6FlagField;
            }
            set {
                this.customFactor6FlagField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        public string UDF1 {
            get {
                return this.uDF1Field;
            }
            set {
                this.uDF1Field = value;
            }
        }
        
        /// <remarks/>
        public string UDF2 {
            get {
                return this.uDF2Field;
            }
            set {
                this.uDF2Field = value;
            }
        }
        
        /// <remarks/>
        public string UDF3 {
            get {
                return this.uDF3Field;
            }
            set {
                this.uDF3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeAnswerResponse6 {
        
        private string relatedConfidenceScoreField;
        
        private string repeatedWordsPctField;
        
        private string detectedLanguageCodeField;
        
        private string rASField;
        
        private string badWordsFlagField;
        
        private string garbageWordsFlagField;
        
        private string nonEngagedFlagField;
        
        private string pastedTextFlagField;
        
        private string robotFlagField;
        
        private string similarityFlagField;
        
        private string badPhraseFlagField;
        
        private string customFactor1FlagField;
        
        private string customFactor2FlagField;
        
        private string customFactor3FlagField;
        
        private string customFactor4FlagField;
        
        private string customFactor5FlagField;
        
        private string customFactor6FlagField;
        
        private string errorMsgField;
        
        private string uDF1Field;
        
        private string uDF2Field;
        
        private string uDF3Field;
        
        /// <remarks/>
        public string RelatedConfidenceScore {
            get {
                return this.relatedConfidenceScoreField;
            }
            set {
                this.relatedConfidenceScoreField = value;
            }
        }
        
        /// <remarks/>
        public string RepeatedWordsPct {
            get {
                return this.repeatedWordsPctField;
            }
            set {
                this.repeatedWordsPctField = value;
            }
        }
        
        /// <remarks/>
        public string DetectedLanguageCode {
            get {
                return this.detectedLanguageCodeField;
            }
            set {
                this.detectedLanguageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RAS {
            get {
                return this.rASField;
            }
            set {
                this.rASField = value;
            }
        }
        
        /// <remarks/>
        public string BadWordsFlag {
            get {
                return this.badWordsFlagField;
            }
            set {
                this.badWordsFlagField = value;
            }
        }
        
        /// <remarks/>
        public string GarbageWordsFlag {
            get {
                return this.garbageWordsFlagField;
            }
            set {
                this.garbageWordsFlagField = value;
            }
        }
        
        /// <remarks/>
        public string NonEngagedFlag {
            get {
                return this.nonEngagedFlagField;
            }
            set {
                this.nonEngagedFlagField = value;
            }
        }
        
        /// <remarks/>
        public string PastedTextFlag {
            get {
                return this.pastedTextFlagField;
            }
            set {
                this.pastedTextFlagField = value;
            }
        }
        
        /// <remarks/>
        public string RobotFlag {
            get {
                return this.robotFlagField;
            }
            set {
                this.robotFlagField = value;
            }
        }
        
        /// <remarks/>
        public string SimilarityFlag {
            get {
                return this.similarityFlagField;
            }
            set {
                this.similarityFlagField = value;
            }
        }
        
        /// <remarks/>
        public string BadPhraseFlag {
            get {
                return this.badPhraseFlagField;
            }
            set {
                this.badPhraseFlagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomFactor1Flag {
            get {
                return this.customFactor1FlagField;
            }
            set {
                this.customFactor1FlagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomFactor2Flag {
            get {
                return this.customFactor2FlagField;
            }
            set {
                this.customFactor2FlagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomFactor3Flag {
            get {
                return this.customFactor3FlagField;
            }
            set {
                this.customFactor3FlagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomFactor4Flag {
            get {
                return this.customFactor4FlagField;
            }
            set {
                this.customFactor4FlagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomFactor5Flag {
            get {
                return this.customFactor5FlagField;
            }
            set {
                this.customFactor5FlagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomFactor6Flag {
            get {
                return this.customFactor6FlagField;
            }
            set {
                this.customFactor6FlagField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        public string UDF1 {
            get {
                return this.uDF1Field;
            }
            set {
                this.uDF1Field = value;
            }
        }
        
        /// <remarks/>
        public string UDF2 {
            get {
                return this.uDF2Field;
            }
            set {
                this.uDF2Field = value;
            }
        }
        
        /// <remarks/>
        public string UDF3 {
            get {
                return this.uDF3Field;
            }
            set {
                this.uDF3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AnalyzeAnswer6CompletedEventHandler(object sender, AnalyzeAnswer6CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnalyzeAnswer6CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AnalyzeAnswer6CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AnalyzeAnswerResponse6 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AnalyzeAnswerResponse6)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AnalyzeAnswer4CompletedEventHandler(object sender, AnalyzeAnswer4CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnalyzeAnswer4CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AnalyzeAnswer4CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AnalyzeAnswerResponse4 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AnalyzeAnswerResponse4)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AnalyzeAnswer5CompletedEventHandler(object sender, AnalyzeAnswer5CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnalyzeAnswer5CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AnalyzeAnswer5CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AnalyzeAnswerResponse4 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AnalyzeAnswerResponse4)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591