//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplication1.psapi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="v2Soap", Namespace="http://tempuri.org/")]
    public partial class v2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnSubscribeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReSubscribeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPartnerUserProfilesListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSurveysOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSurveysHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateProfileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public v2() {
            this.Url = global::WebApplication1.Properties.Settings.Default.WebApplication1_psapi_v2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UnSubscribeCompletedEventHandler UnSubscribeCompleted;
        
        /// <remarks/>
        public event ReSubscribeCompletedEventHandler ReSubscribeCompleted;
        
        /// <remarks/>
        public event GetPartnerUserProfilesListCompletedEventHandler GetPartnerUserProfilesListCompleted;
        
        /// <remarks/>
        public event GetSurveysCompletedEventHandler GetSurveysCompleted;
        
        /// <remarks/>
        public event GetSurveysHistoryCompletedEventHandler GetSurveysHistoryCompleted;
        
        /// <remarks/>
        public event UpdateProfileCompletedEventHandler UpdateProfileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Create", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Create(int RID, string TxId, string ExtMemberId, string Country, string State, string FirstName, string LastName, string EmailAddress, string Zip, string Gender, string Dob, string Address1, string Address2, string Ethnicity, string City) {
            object[] results = this.Invoke("Create", new object[] {
                        RID,
                        TxId,
                        ExtMemberId,
                        Country,
                        State,
                        FirstName,
                        LastName,
                        EmailAddress,
                        Zip,
                        Gender,
                        Dob,
                        Address1,
                        Address2,
                        Ethnicity,
                        City});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(int RID, string TxId, string ExtMemberId, string Country, string State, string FirstName, string LastName, string EmailAddress, string Zip, string Gender, string Dob, string Address1, string Address2, string Ethnicity, string City) {
            this.CreateAsync(RID, TxId, ExtMemberId, Country, State, FirstName, LastName, EmailAddress, Zip, Gender, Dob, Address1, Address2, Ethnicity, City, null);
        }
        
        /// <remarks/>
        public void CreateAsync(
                    int RID, 
                    string TxId, 
                    string ExtMemberId, 
                    string Country, 
                    string State, 
                    string FirstName, 
                    string LastName, 
                    string EmailAddress, 
                    string Zip, 
                    string Gender, 
                    string Dob, 
                    string Address1, 
                    string Address2, 
                    string Ethnicity, 
                    string City, 
                    object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        RID,
                        TxId,
                        ExtMemberId,
                        Country,
                        State,
                        FirstName,
                        LastName,
                        EmailAddress,
                        Zip,
                        Gender,
                        Dob,
                        Address1,
                        Address2,
                        Ethnicity,
                        City}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Update(
                    string UserGuid, 
                    int RID, 
                    string ExtMemberId, 
                    string TxId, 
                    string Country, 
                    string State, 
                    string FirstName, 
                    string LastName, 
                    string EmailAddress, 
                    string Zip, 
                    string Gender, 
                    string Dob, 
                    string Address1, 
                    string Address2, 
                    string Ethnicity, 
                    string City) {
            object[] results = this.Invoke("Update", new object[] {
                        UserGuid,
                        RID,
                        ExtMemberId,
                        TxId,
                        Country,
                        State,
                        FirstName,
                        LastName,
                        EmailAddress,
                        Zip,
                        Gender,
                        Dob,
                        Address1,
                        Address2,
                        Ethnicity,
                        City});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(
                    string UserGuid, 
                    int RID, 
                    string ExtMemberId, 
                    string TxId, 
                    string Country, 
                    string State, 
                    string FirstName, 
                    string LastName, 
                    string EmailAddress, 
                    string Zip, 
                    string Gender, 
                    string Dob, 
                    string Address1, 
                    string Address2, 
                    string Ethnicity, 
                    string City) {
            this.UpdateAsync(UserGuid, RID, ExtMemberId, TxId, Country, State, FirstName, LastName, EmailAddress, Zip, Gender, Dob, Address1, Address2, Ethnicity, City, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(
                    string UserGuid, 
                    int RID, 
                    string ExtMemberId, 
                    string TxId, 
                    string Country, 
                    string State, 
                    string FirstName, 
                    string LastName, 
                    string EmailAddress, 
                    string Zip, 
                    string Gender, 
                    string Dob, 
                    string Address1, 
                    string Address2, 
                    string Ethnicity, 
                    string City, 
                    object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        UserGuid,
                        RID,
                        ExtMemberId,
                        TxId,
                        Country,
                        State,
                        FirstName,
                        LastName,
                        EmailAddress,
                        Zip,
                        Gender,
                        Dob,
                        Address1,
                        Address2,
                        Ethnicity,
                        City}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UnSubscribe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UnSubscribe(int Rid, string UserName) {
            object[] results = this.Invoke("UnSubscribe", new object[] {
                        Rid,
                        UserName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UnSubscribeAsync(int Rid, string UserName) {
            this.UnSubscribeAsync(Rid, UserName, null);
        }
        
        /// <remarks/>
        public void UnSubscribeAsync(int Rid, string UserName, object userState) {
            if ((this.UnSubscribeOperationCompleted == null)) {
                this.UnSubscribeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnSubscribeOperationCompleted);
            }
            this.InvokeAsync("UnSubscribe", new object[] {
                        Rid,
                        UserName}, this.UnSubscribeOperationCompleted, userState);
        }
        
        private void OnUnSubscribeOperationCompleted(object arg) {
            if ((this.UnSubscribeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnSubscribeCompleted(this, new UnSubscribeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReSubscribe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReSubscribe(string UserGuid) {
            object[] results = this.Invoke("ReSubscribe", new object[] {
                        UserGuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReSubscribeAsync(string UserGuid) {
            this.ReSubscribeAsync(UserGuid, null);
        }
        
        /// <remarks/>
        public void ReSubscribeAsync(string UserGuid, object userState) {
            if ((this.ReSubscribeOperationCompleted == null)) {
                this.ReSubscribeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReSubscribeOperationCompleted);
            }
            this.InvokeAsync("ReSubscribe", new object[] {
                        UserGuid}, this.ReSubscribeOperationCompleted, userState);
        }
        
        private void OnReSubscribeOperationCompleted(object arg) {
            if ((this.ReSubscribeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReSubscribeCompleted(this, new ReSubscribeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPartnerUserProfilesList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPartnerUserProfilesList(string UserGuid) {
            object[] results = this.Invoke("GetPartnerUserProfilesList", new object[] {
                        UserGuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPartnerUserProfilesListAsync(string UserGuid) {
            this.GetPartnerUserProfilesListAsync(UserGuid, null);
        }
        
        /// <remarks/>
        public void GetPartnerUserProfilesListAsync(string UserGuid, object userState) {
            if ((this.GetPartnerUserProfilesListOperationCompleted == null)) {
                this.GetPartnerUserProfilesListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPartnerUserProfilesListOperationCompleted);
            }
            this.InvokeAsync("GetPartnerUserProfilesList", new object[] {
                        UserGuid}, this.GetPartnerUserProfilesListOperationCompleted, userState);
        }
        
        private void OnGetPartnerUserProfilesListOperationCompleted(object arg) {
            if ((this.GetPartnerUserProfilesListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPartnerUserProfilesListCompleted(this, new GetPartnerUserProfilesListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSurveys", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSurveys(string UserGuid) {
            object[] results = this.Invoke("GetSurveys", new object[] {
                        UserGuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSurveysAsync(string UserGuid) {
            this.GetSurveysAsync(UserGuid, null);
        }
        
        /// <remarks/>
        public void GetSurveysAsync(string UserGuid, object userState) {
            if ((this.GetSurveysOperationCompleted == null)) {
                this.GetSurveysOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSurveysOperationCompleted);
            }
            this.InvokeAsync("GetSurveys", new object[] {
                        UserGuid}, this.GetSurveysOperationCompleted, userState);
        }
        
        private void OnGetSurveysOperationCompleted(object arg) {
            if ((this.GetSurveysCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSurveysCompleted(this, new GetSurveysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSurveysHistory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSurveysHistory(string UserGuid) {
            object[] results = this.Invoke("GetSurveysHistory", new object[] {
                        UserGuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSurveysHistoryAsync(string UserGuid) {
            this.GetSurveysHistoryAsync(UserGuid, null);
        }
        
        /// <remarks/>
        public void GetSurveysHistoryAsync(string UserGuid, object userState) {
            if ((this.GetSurveysHistoryOperationCompleted == null)) {
                this.GetSurveysHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSurveysHistoryOperationCompleted);
            }
            this.InvokeAsync("GetSurveysHistory", new object[] {
                        UserGuid}, this.GetSurveysHistoryOperationCompleted, userState);
        }
        
        private void OnGetSurveysHistoryOperationCompleted(object arg) {
            if ((this.GetSurveysHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSurveysHistoryCompleted(this, new GetSurveysHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateProfile(string xml) {
            object[] results = this.Invoke("UpdateProfile", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateProfileAsync(string xml) {
            this.UpdateProfileAsync(xml, null);
        }
        
        /// <remarks/>
        public void UpdateProfileAsync(string xml, object userState) {
            if ((this.UpdateProfileOperationCompleted == null)) {
                this.UpdateProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProfileOperationCompleted);
            }
            this.InvokeAsync("UpdateProfile", new object[] {
                        xml}, this.UpdateProfileOperationCompleted, userState);
        }
        
        private void OnUpdateProfileOperationCompleted(object arg) {
            if ((this.UpdateProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProfileCompleted(this, new UpdateProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UnSubscribeCompletedEventHandler(object sender, UnSubscribeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnSubscribeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnSubscribeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReSubscribeCompletedEventHandler(object sender, ReSubscribeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReSubscribeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReSubscribeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetPartnerUserProfilesListCompletedEventHandler(object sender, GetPartnerUserProfilesListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPartnerUserProfilesListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPartnerUserProfilesListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetSurveysCompletedEventHandler(object sender, GetSurveysCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSurveysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSurveysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetSurveysHistoryCompletedEventHandler(object sender, GetSurveysHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSurveysHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSurveysHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateProfileCompletedEventHandler(object sender, UpdateProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591