//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.v2Soap")]
    public interface v2Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Create(int RID, string TxId, string ExtMemberId, string Country, string State, string FirstName, string LastName, string EmailAddress, string Zip, string Gender, string Dob, string Address1, string Address2, string Ethnicity, string City);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CreateAsync(int RID, string TxId, string ExtMemberId, string Country, string State, string FirstName, string LastName, string EmailAddress, string Zip, string Gender, string Dob, string Address1, string Address2, string Ethnicity, string City);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Update(
                    string UserGuid, 
                    int RID, 
                    string ExtMemberId, 
                    string TxId, 
                    string Country, 
                    string State, 
                    string FirstName, 
                    string LastName, 
                    string EmailAddress, 
                    string Zip, 
                    string Gender, 
                    string Dob, 
                    string Address1, 
                    string Address2, 
                    string Ethnicity, 
                    string City);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateAsync(
                    string UserGuid, 
                    int RID, 
                    string ExtMemberId, 
                    string TxId, 
                    string Country, 
                    string State, 
                    string FirstName, 
                    string LastName, 
                    string EmailAddress, 
                    string Zip, 
                    string Gender, 
                    string Dob, 
                    string Address1, 
                    string Address2, 
                    string Ethnicity, 
                    string City);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnSubscribe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UnSubscribe(int Rid, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnSubscribe", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UnSubscribeAsync(int Rid, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReSubscribe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReSubscribe(string UserGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReSubscribe", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReSubscribeAsync(string UserGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnerUserProfilesList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPartnerUserProfilesList(string UserGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnerUserProfilesList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPartnerUserProfilesListAsync(string UserGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSurveys", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSurveys(string UserGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSurveys", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSurveysAsync(string UserGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSurveysHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSurveysHistory(string UserGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSurveysHistory", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSurveysHistoryAsync(string UserGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateProfile(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateProfileAsync(string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface v2SoapChannel : WebApplication1.ServiceReference1.v2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class v2SoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.v2Soap>, WebApplication1.ServiceReference1.v2Soap {
        
        public v2SoapClient() {
        }
        
        public v2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public v2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public v2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public v2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Create(int RID, string TxId, string ExtMemberId, string Country, string State, string FirstName, string LastName, string EmailAddress, string Zip, string Gender, string Dob, string Address1, string Address2, string Ethnicity, string City) {
            return base.Channel.Create(RID, TxId, ExtMemberId, Country, State, FirstName, LastName, EmailAddress, Zip, Gender, Dob, Address1, Address2, Ethnicity, City);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(int RID, string TxId, string ExtMemberId, string Country, string State, string FirstName, string LastName, string EmailAddress, string Zip, string Gender, string Dob, string Address1, string Address2, string Ethnicity, string City) {
            return base.Channel.CreateAsync(RID, TxId, ExtMemberId, Country, State, FirstName, LastName, EmailAddress, Zip, Gender, Dob, Address1, Address2, Ethnicity, City);
        }
        
        public string Update(
                    string UserGuid, 
                    int RID, 
                    string ExtMemberId, 
                    string TxId, 
                    string Country, 
                    string State, 
                    string FirstName, 
                    string LastName, 
                    string EmailAddress, 
                    string Zip, 
                    string Gender, 
                    string Dob, 
                    string Address1, 
                    string Address2, 
                    string Ethnicity, 
                    string City) {
            return base.Channel.Update(UserGuid, RID, ExtMemberId, TxId, Country, State, FirstName, LastName, EmailAddress, Zip, Gender, Dob, Address1, Address2, Ethnicity, City);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(
                    string UserGuid, 
                    int RID, 
                    string ExtMemberId, 
                    string TxId, 
                    string Country, 
                    string State, 
                    string FirstName, 
                    string LastName, 
                    string EmailAddress, 
                    string Zip, 
                    string Gender, 
                    string Dob, 
                    string Address1, 
                    string Address2, 
                    string Ethnicity, 
                    string City) {
            return base.Channel.UpdateAsync(UserGuid, RID, ExtMemberId, TxId, Country, State, FirstName, LastName, EmailAddress, Zip, Gender, Dob, Address1, Address2, Ethnicity, City);
        }
        
        public string UnSubscribe(int Rid, string UserName) {
            return base.Channel.UnSubscribe(Rid, UserName);
        }
        
        public System.Threading.Tasks.Task<string> UnSubscribeAsync(int Rid, string UserName) {
            return base.Channel.UnSubscribeAsync(Rid, UserName);
        }
        
        public string ReSubscribe(string UserGuid) {
            return base.Channel.ReSubscribe(UserGuid);
        }
        
        public System.Threading.Tasks.Task<string> ReSubscribeAsync(string UserGuid) {
            return base.Channel.ReSubscribeAsync(UserGuid);
        }
        
        public string GetPartnerUserProfilesList(string UserGuid) {
            return base.Channel.GetPartnerUserProfilesList(UserGuid);
        }
        
        public System.Threading.Tasks.Task<string> GetPartnerUserProfilesListAsync(string UserGuid) {
            return base.Channel.GetPartnerUserProfilesListAsync(UserGuid);
        }
        
        public string GetSurveys(string UserGuid) {
            return base.Channel.GetSurveys(UserGuid);
        }
        
        public System.Threading.Tasks.Task<string> GetSurveysAsync(string UserGuid) {
            return base.Channel.GetSurveysAsync(UserGuid);
        }
        
        public string GetSurveysHistory(string UserGuid) {
            return base.Channel.GetSurveysHistory(UserGuid);
        }
        
        public System.Threading.Tasks.Task<string> GetSurveysHistoryAsync(string UserGuid) {
            return base.Channel.GetSurveysHistoryAsync(UserGuid);
        }
        
        public string UpdateProfile(string xml) {
            return base.Channel.UpdateProfile(xml);
        }
        
        public System.Threading.Tasks.Task<string> UpdateProfileAsync(string xml) {
            return base.Channel.UpdateProfileAsync(xml);
        }
    }
}
